### ISSUE TITLE
Application locked up when trying to load image

### ISSUE THREAD

**Issue by rlarmore** [viezel/NappImageView#11]
I am opening 5 or more images in a tableView, some of the them load while the last one seems to hang the application. 

[INFO] :   CFNetwork SSLHandshake failed (-9806)
[INFO] :   CFNetwork SSLHandshake failed (-9802)
[INFO] :   CFNetwork SSLHandshake failed (-9802)
[INFO] :   NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
[WARN] :   NappImageView :: WARN :: Loading image failed: ....Utah_Rainbow_Arch.jpg
[WARN] :   NappImageView :: WARN :: Loading image failed: ....Utah_Rainbow_Arch.jpg
[WARN] :   NappImageView :: WARN :: Loading image failed: ....Utah_Rainbow_Arch.jpg

// Code....
    var imageBack = NappImageView.createImageView({
        height: pHeight,
        width: newWidth,
        contentMode: NappImageView.CONTENT_MODE_ASPECT_FIT,
        clipsToBounds: true,
        image: trips[i].imageUrl
    });

Thanks!

**Comment by viezel** [comment]
Looks  like it's an SSL certificate bug

**Comment by viezel** [comment]
Meaning it has nothing to do with the module itself.
